#!/bin/sh
#/etc/init.d/resistor

APPDIR=/opt/resistor
PID=/var/run/resistor.pid

case "$1" in
   start)
     echo "Starting resistor"
	   export PWD=$APPDIR
     start-stop-daemon --start --quiet --make-pidfile --pidfile $PID --chdir $APPDIR --background --exec ./resistor -- -config $APPDIR/conf/config.toml -logs $APPDIR/log
     ;;
   stop)
     echo "Stopping resistor"
     start-stop-daemon --stop --pidfile $PID
	 rm -f $PID
     ;;
   *)
     echo "Usage: /etc/init.d/resistor{start|stop}"
     exit 1
     ;;
esac

exit 0
