export const AlertComponentConfig: any =
  {
    'name' : 'Alert Definitions',
    'table-columns' : [
      { 'title': 'ID', 'name': 'ID' },
      { 'title': 'Active', 'name': 'Active' },
      { 'title': 'BaselineID', 'name': 'BaselineID' },
      { 'title': 'ProductID', 'name': 'ProductID' },
      { 'title': 'AlertGroup', 'name': 'AlertGroup' },
      { 'title': 'NumAlertID', 'name': 'NumAlertID' },
      { 'title': 'InfluxDB', 'name': 'InfluxDB' },
      { 'title': 'InfluxRP', 'name': 'InfluxRP' },
      { 'title': 'InfluxMeasurement', 'name': 'InfluxMeasurement' },
      { 'title': 'TagDescription', 'name': 'TagDescription' },
      { 'title': 'InfluxFilter', 'name': 'InfluxFilter' },
      { 'title': 'TriggerType', 'name': 'TriggerType' },
      { 'title': 'IntervalCheck', 'name': 'IntervalCheck' },
      { 'title': 'OperationID', 'name': 'OperationID' },
      { 'title': 'Field', 'name': 'Field' },
      { 'title': 'FieldDesc', 'name': 'FieldDesc' },
      { 'title': 'StatFunc', 'name': 'StatFunc' },
      { 'title': 'ExtraData', 'name': 'ExtraData' },
      { 'title': 'CritDirection', 'name': 'CritDirection' },
      { 'title': 'Shift', 'name': 'Shift' },
      { 'title': 'TrendType', 'name': 'TrendType' },
      { 'title': 'TrendSign', 'name': 'TrendSign' },
      { 'title': 'ThCritRangeTimeID', 'name': 'ThCritRangeTimeID' },
      { 'title': 'ThWarnRangeTimeID', 'name': 'ThWarnRangeTimeID' },
      { 'title': 'ThInfoRangeTimeID', 'name': 'ThInfoRangeTimeID' },
      { 'title': 'ThCritDef', 'name': 'ThCritDef' },
      { 'title': 'ThWarnDef', 'name': 'ThWarnDef' },
      { 'title': 'ThInfoDef', 'name': 'ThInfoDef' },
      { 'title': 'ThCritEx1', 'name': 'ThCritEx1' },
      { 'title': 'ThWarnEx1', 'name': 'ThWarnEx1' },
      { 'title': 'ThInfoEx1', 'name': 'ThInfoEx1' },
      { 'title': 'ThCritEx2', 'name': 'ThCritEx2' },
      { 'title': 'ThWarnEx2', 'name': 'ThWarnEx2' },
      { 'title': 'ThInfoEx2', 'name': 'ThInfoEx2' },
      { 'title': 'GrafanaServer', 'name': 'GrafanaServer' },
      { 'title': 'GrafanaDashLabel', 'name': 'GrafanaDashLabel' },
      { 'title': 'GrafanaDashPanelID', 'name': 'GrafanaDashPanelID' },
      { 'title': 'ProductTag', 'name': 'ProductTag' },
      { 'title': 'DeviceIDLabel', 'name': 'DeviceIDLabel' },
      { 'title': 'ExtraTag', 'name': 'ExtraTag' },
      { 'title': 'ExtraLabel', 'name': 'ExtraLabel' },
      { 'title': 'AlertExtraText', 'name': 'AlertExtraText' },
      { 'title': 'KapacitorID', 'name': 'KapacitorID' },
      { 'title': 'OutHTTP', 'name': 'OutHTTP' }
    ],
    'slug' : 'alertcfg'
  };

  export const TableRole : string = 'fulledit';
  export const OverrideRoleActions : Array<Object> = [
    {'name':'export', 'type':'icon', 'icon' : 'glyphicon glyphicon-download-alt text-info', 'tooltip': 'Export item'},
    {'name':'view', 'type':'icon', 'icon' : 'glyphicon glyphicon-eye-open text-success', 'tooltip': 'View item'},
    {'name':'edit', 'type':'icon', 'icon' : 'glyphicon glyphicon-edit text-warning', 'tooltip': 'Edit item'},
    {'name':'remove', 'type':'icon', 'icon' : 'glyphicon glyphicon glyphicon-remove text-danger', 'tooltip': 'Remove item'},
    {'name':'deploy', 'type':'icon', 'icon' : 'glyphicon glyphicon glyphicon-play text-warning', 'tooltip': 'Deploy item'},
  ]
